substitutions:
  _LOCATION: asia-southeast1
  _REPOSITORY: security-gate
  _SERVICE: go-sast
  _TAG: latest

steps:
  - id: build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/go-sast:${_TAG}
      - .

  - id: push
    name: gcr.io/cloud-builders/docker
    waitFor:
      - build
    args:
      - push
      - ${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/go-sast:${_TAG}

  - id: deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    waitFor:
      - push
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/go-sast:${_TAG}
      - --region=${_LOCATION}
      - --platform=managed
      - --port=8080
      - --allow-unauthenticated
      - --quiet

images:
  - ${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/go-sast:${_TAG}

options:
  logging: CLOUD_LOGGING_ONLY
