substitutions:
  _LOCATION: asia-southeast1
  _REPOSITORY: security-gate
  _TAG: latest

steps:
  - id: build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/go-sast:${_TAG}
      - .

  - id: push
    name: gcr.io/cloud-builders/docker
    waitFor:
      - build
    args:
      - push
      - ${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/go-sast:${_TAG}

images:
  - ${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/go-sast:${_TAG}

options:
  logging: CLOUD_LOGGING_ONLY
